YawmanTrainingBundle_default:
        resource: "@YawmanTrainingBundle/Controller/DefaultController.php"
        type: annotation
    
YawmanTrainingBundle_dashboard:
        resource: "@YawmanTrainingBundle/Controller/DashboardController.php"
        type: annotation
    
YawmanTrainingBundle_user:
        resource: "@YawmanTrainingBundle/Controller/UserController.php"
        type: annotation

YawmanTrainingBundle_company:
        resource: "@YawmanTrainingBundle/Controller/CompanyController.php"
        type: annotation

YawmanTrainingBundle_lesson:
        resource: "@YawmanTrainingBundle/Controller/LessonController.php"
        type: annotation

YawmanTrainingBundle_lessonplan:
        resource: "@YawmanTrainingBundle/Controller/LessonPlanController.php"
        type: annotation

YawmanTrainingBundle_userlesson:
        resource: "@YawmanTrainingBundle/Controller/UserLessonController.php"
        type: annotation