homepage:
    pattern:  /
    defaults: { _controller: YawmanTrainingBundle:Default:index }
    
YawmanTrainingBundle_dashboard:
        resource: "@YawmanTrainingBundle/Resources/config/routing/dashboard.yml"
        prefix:   /dashboard
    
YawmanTrainingBundle_user:
        resource: "@YawmanTrainingBundle/Controller/UserController.php"
        type: annotation

YawmanTrainingBundle_company:
        resource: "@YawmanTrainingBundle/Controller/CompanyController.php"
        type: annotation

YawmanTrainingBundle_lesson:
        resource: "@YawmanTrainingBundle/Resources/config/routing/lesson.yml"
        prefix:   /lesson

YawmanTrainingBundle_lessonplan:
        resource: "@YawmanTrainingBundle/Resources/config/routing/lessonplan.yml"
        prefix:   /lesson-plan