parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     com_us_ipt_training
    database_user:     root
    database_password: cnasty328

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
