jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Yawman\TrainingBundle\Entity\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          entity: { class: YawmanTrainingBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
           pattern:    ^/login$
           anonymous:  ~

        registration_firewall:
           pattern:    ^/registration$
           anonymous:  ~

        register_firewall:
           pattern:    ^/register$
           anonymous:  ~

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                always_use_default_target_path: true
                default_target_path: /dashboard
            logout:
                path: /logout
                target: /

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/management, roles: ROLE_MANAGER }
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/, roles: ROLE_USER }