admin:
    pattern: /
    defaults: { _controller: YawmanTrainingBundle:Admin:index }

admin_company:
    pattern:  /company
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyList" }

admin_company_show:
    pattern:  /company/{id}/show
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyShow" }

admin_company_new:
    pattern:  /company/new
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyNew" }

admin_company_create:
    pattern:  /company/create
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyCreate" }
    requirements: { _method: post }

admin_company_edit:
    pattern:  /company/{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyEdit" }

admin_company_update:
    pattern:  /company/{id}/update
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyUpdate" }
    requirements: { _method: post }

admin_company_delete:
    pattern:  /company/{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:Admin:companyDelete" }
    requirements: { _method: post }
    
admin_user:
    pattern:  /user
    defaults: { _controller: "YawmanTrainingBundle:Admin:userList" }

admin_user_show:
    pattern:  /user/{id}/show
    defaults: { _controller: "YawmanTrainingBundle:Admin:userShow" }

admin_user_new:
    pattern:  /user/new
    defaults: { _controller: "YawmanTrainingBundle:Admin:userNew" }

admin_user_create:
    pattern:  /user/create
    defaults: { _controller: "YawmanTrainingBundle:Admin:userCreate" }
    requirements: { _method: post }

admin_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:Admin:userEdit" }

admin_user_update:
    pattern:  /user/{id}/update
    defaults: { _controller: "YawmanTrainingBundle:Admin:userUpdate" }
    requirements: { _method: post }

admin_user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:Admin:userDelete" }
    requirements: { _method: post }

admin_group:
    pattern:  /group
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupList" }

admin_group_show:
    pattern:  /group/{id}/show
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupShow" }

admin_group_new:
    pattern:  /group/new
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupNew" }

admin_group_create:
    pattern:  /group/create
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupCreate" }
    requirements: { _method: post }

admin_group_edit:
    pattern:  /group/{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupEdit" }

admin_group_update:
    pattern:  /group/{id}/update
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupUpdate" }
    requirements: { _method: post }

admin_group_delete:
    pattern:  /group/{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:Admin:groupDelete" }
    requirements: { _method: post }

admin_lesson:
    pattern:  /lesson
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonList" }

admin_lesson_show:
    pattern:  /lesson/{id}/show
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonShow" }

admin_lesson_new:
    pattern:  /lesson/new
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonNew" }

admin_lesson_create:
    pattern:  /lesson/create
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonCreate" }
    requirements: { _method: post }

admin_lesson_edit:
    pattern:  /lesson/{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonEdit" }

admin_lesson_update:
    pattern:  /lesson/{id}/update
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonUpdate" }
    requirements: { _method: post }

admin_lesson_delete:
    pattern:  /lesson/{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonDelete" }
    requirements: { _method: post }

admin_lessonplan:
    pattern:  /lesson-plan
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanList" }

admin_lessonplan_show:
    pattern:  /lesson-plan/{id}/show
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanShow" }

admin_lessonplan_new:
    pattern:  /lesson-plan/new
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanNew" }

admin_lessonplan_create:
    pattern:  /lesson-plan/create
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanCreate" }
    requirements: { _method: post }

admin_lessonplan_edit:
    pattern:  /lesson-plan/{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanEdit" }

admin_lessonplan_update:
    pattern:  /lesson-plan/{id}/update
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanUpdate" }
    requirements: { _method: post }

admin_lessonplan_delete:
    pattern:  /lesson-plan/{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:Admin:lessonPlanDelete" }
    requirements: { _method: post }