lesson:
    pattern:  /
    defaults: { _controller: "YawmanTrainingBundle:Lesson:index" }

lesson_show:
    pattern:  /{id}/show
    defaults: { _controller: "YawmanTrainingBundle:Lesson:show" }

lesson_new:
    pattern:  /new
    defaults: { _controller: "YawmanTrainingBundle:Lesson:new" }

lesson_create:
    pattern:  /create
    defaults: { _controller: "YawmanTrainingBundle:Lesson:create" }
    requirements: { _method: post }

lesson_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:Lesson:edit" }

lesson_update:
    pattern:  /{id}/update
    defaults: { _controller: "YawmanTrainingBundle:Lesson:update" }
    requirements: { _method: post }

lesson_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:Lesson:delete" }
    requirements: { _method: post }