lessonplan:
    pattern:  /
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:index" }

lessonplan_show:
    pattern:  /{id}/show
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:show" }

lessonplan_new:
    pattern:  /new
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:new" }

lessonplan_create:
    pattern:  /create
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:create" }
    requirements: { _method: post }

lessonplan_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:edit" }

lessonplan_update:
    pattern:  /{id}/update
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:update" }
    requirements: { _method: post }

lessonplan_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "YawmanTrainingBundle:LessonPlan:delete" }
    requirements: { _method: post }